language: node_js

node_js:
  - 'node'
  - '7'
  - '6'
  - '4'
  - 'iojs'
  - '0.12'
  - '0.10'

script:
  - npm test

addons:
  code_climate:
    repo_token: fe7918d81d3b16b08cae49cd6fe5ecc9e0b04c713cc219b77bbe1188cae02e1a

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
